# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: booking_postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: admin
      POSTGRES_DB: db01
      PGDATA: /home/ubuntu/postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - 54321:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
