# Generated by Django 4.2.7 on 2024-04-20 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_office_is_active_room_is_active_seat_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
